### ISSUE TITLE
No Update because of what Issues?

### ISSUE THREAD

**Issue by stefan-b314** [ilovecode1/cosmic-normalizer#2]
Hi,

in your README it reads: 

> Cosmic Normalizer will nut be updated on the store for now because of issues.

Can you explain, what these issues are? Maybe I can help to fix them.

Kind Regards,
Stefan

**Comment by CosmicWebServices** [comment]
I try to upload and there is a error about broken links

**Comment by stefan-b314** [comment]
Maybe, you can post the exact message here?!

**Comment by CosmicWebServices** [comment]
Sorry it took me long but, I am now moving to a new computer so the issues might not be there I will try to update soon. Thanks for helping out.
